### PR TITLE
Expert Reviewed changes

### PR DESCRIPTION
**Pull request by strbean**
Implement the changes specified here: https://docs.google.com/presentation/d/1VuWmLXl39fJYqlYn0mStoPkUDeKzIcYhO8kZOcG1wXM/edit

and additional notes here:
https://docs.google.com/document/d/1-9SBeLRVnPiKgntt6bByAH7J75lM7J0ha7ESe2UmqAk/edit

Also, #108

### CODE REVIEW

**Comment by maryjgoldman** [comment]
Great! Where can I view these changes? I believe we need to set up a beta testing place, correct?

**Comment by strbean** [comment]
It's live on http://brcaexchange.cloudapp.net

**Comment by maryjgoldman** [comment]
Looks really good!! Just a few comments/changes:
- The labels for the variant table are aligned a bit wonky. I know Brian (Craft) had trouble with these too. Is there a way to make them all appear left or center aligned (whatever is easiest)? Also, can we make the clinical significance column wider so that each variant takes up no more than 2 lines?
- Contrary to what will be displayed in the 'All Data' pages, the Supporting Evidence URL(s) in this case is always ONLY a link to the http://hci-exlovd.hci.utah.edu/variants.php page. In the 'All Data' pages this will include links to pubmed, etc, that you have done here, but on the 'Expert Reviewed' pages it's only to the HCI page.
- Date Last Evaluated: 10 August 15 ---> 10 August 2015
- Label of 'Protein Abbrev' in details page --> 'Abbreviated AA Change'

**Comment by maryjgoldman** [comment]
Also, can all the links open in new tabs? Sorry I didn't indicate that on the wireframes!

**Comment by strbean** [comment]
With regards to Supporting Evidence URL: just to double check, this
corresponds to the URL_ENIGMA column in the table, correct?

For the Protein Abbrev, getting a different heading between the search
results and the variant display has proven difficult, I'll work on it.

**Comment by maryjgoldman** [comment]
I'll let @melissacline comment about the URL since I don't have access to the table. An initial look says no? It doesn't look like it is filled in for many variants.

Yes, I suspected as much about the different heading. If it ends up being too difficult we can push back and ask them if it's ok to leave as is.

**Comment by melissacline** [comment]
Yes, the Supporting Evidence link should be from the URL_ENIGMA field.
That was the data they wanted.

For the differences in heading between the variant table and the variant
details page, we can definitely push back if it proves difficult (as it
already has, from the sound of things).  As you'll hear on the call
tomorrow, our users are scientists who aren't necessarily computational,
and while they might have their vision of the functionality they want, they
rely on us to clarify what's easy and what's hard.

**Comment by maryjgoldman** [comment]
More feedback:
- on the variants table, need to remove the 'NM_ ...' and 'NP_ ... ' from the Nucleotide and Protein columns
- we got feedback that for the Enigma rules, link to this website instead: https://enigmaconsortium.org/library/general-documents/

**Comment by strbean** [comment]
I was (nearly) able to fix the issues with the table heading. I've attached
screenshots of the new behavior. The only remaining problem is the sorting
buttons will just barely clip with the text at certain screen sizes.
Unfortunately trying to pad the text to stop this leads to extremely wonky
alignment once the columns get squeezed down enough that they take up two
rows.

**Pull request merged**
